LengKeng/Models/ACCOUNTS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LengKeng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNTS()
        {
            this.BILL = new HashSet<BILL>();
            this.COMMENTS = new HashSet<COMMENTS>();
            this.SUPPORT = new HashSet<SUPPORT>();
        }
    
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public int ADMIN { get; set; }
        public string FULLNAME { get; set; }
        public string BIRTHDAY { get; set; }
        public string SEX { get; set; }
        public string EMAIL { get; set; }
        public string PHONENUMBER { get; set; }
        public string ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPORT> SUPPORT { get; set; }
    }
}

LengKeng/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LengKeng.Models;
using LengKeng.code;
using LengKeng.Code;
using System.Net.Mail;

namespace LengKeng.Controllers
{
    public class AccountsController : Controller
    {
        //
        // GET: /Accounts/
        private AccountModelProcess AccM = new AccountModelProcess();
        private ShoppingCart SCart = new ShoppingCart();

        

        [HttpGet]
        public ActionResult LoginAccount()
        {
            return View("Login", new LoginModel());
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            UserSession user = SessionHelper.getSesstion();
            if (user != null)
            {
                if (user.isSocial == 0)
                {
                    return View("ChangePassword");
                }
                
            }
            return RedirectToAction("Index", "Home");
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                UserSession user = SessionHelper.getSesstion();
                if (user != null)
                {
                    if (user.isSocial == 0)
                    {
                        if (AccM.changePassword(model))
                        {
                            return View("ChangePasswordSuccess");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Mật khẩu không đúng");
                            return View("ChangePassword", model);
                        }
                    }

                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Vui lòng điền đủ thông tin");
                return View("ChangePassword", model);
            }
        }

        [HttpGet]
        public ActionResult RecoverPassword()
        {
            return View("RecoverPassword");
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult RecoverPassword(ResetPasswordModel model)
        {
            if (ModelState.IsValid)
            {
                
                        if (AccM.resetPassword(model))
                        {
                            return View("RecoverPasswordSuccess");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Tên tài khoản không tồn tại");
                            return View("RecoverPassword", model);
                        }
                
            }
            else
            {
                ModelState.AddModelError("", "Vui lòng điền đủ thông tin");
                return View("RecoverPassword", model);
            }
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginAccount(LoginModel model)
        {
            if (AccM.login(model.UserName, model.Password) && ModelState.IsValid)
            {
                SessionHelper.setSesstion(new UserSession() { UserName = model.UserName, Admin = AccM.isAdmin(model.UserName), isSocial = 0 });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Tên tài khoàn trùng");
                return View("Login", new LoginModel());
            }

        }

        [HttpPost]
        public ActionResult LoginBySocial(string email)
        {
            AccM.loginBySocial(email);
            return Json("/Home/Index", JsonRequestBehavior.AllowGet);
        }



        public ActionResult detailAccount()
        {
            UserSession user = SessionHelper.getSesstion();
            if (user != null)
            {
                ViewData["acc"] = AccM.getAccount(user.UserName);
                return View("DetailAccount");
            }
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public ActionResult updateAccount()
        {
            UserSession user = SessionHelper.getSesstion();
            if (user != null)
            {
                ProfileUserModel model = AccM.getAccount(user.UserName);

                
                return View("UpdateAccount", model);
            }
            return RedirectToAction("Index", "Home");



           
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult processUpdateAccount(ProfileUserModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AccM.updateAccount(model);
                    return RedirectToAction("detailAccount");
                }
                else
                {
                    ModelState.AddModelError("fail1", "Vui lòng điền đầy đủ thông tin");
                    return View("UpdateAccount", model);
                }
            }
            catch
            {
                ModelState.AddModelError("fail2", "Đã có lỗi, cập nhật không thành công");
                return View("UpdateAccount", model);
            }

        }


        public ActionResult Logout()
        {
            SessionHelper.setSesstion(null);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult registerAccount()
        {
            return View("RegisterAccount", new Models.ProfileUserModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult registerAccount(ProfileUserModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (AccM.addAccount(model))
                    {
                        UserSession user = SessionHelper.getSesstion();
                        if (user == null)
                        {
                            SessionHelper.setSesstion(new UserSession() { UserName = model.username, Admin = 0 });
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            if (user.Admin == 0)
                            {
                                SessionHelper.setSesstion(new UserSession() { UserName = model.username, Admin = 0 });
                                return RedirectToAction("Index", "Home");
                            }
                            else
                            {
                                return RedirectToAction("manageAccounts");
                            }
                        }
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }

                   
                       
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Vui lòng điền đầy đủ thông tin");
                    return View(model);
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Đã có lỗi, tạo tài khoản không thành công");
                return View(model);
            }
        }


        //[HttpGet]
        //public ActionResult manageAccounts()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            ViewData["Listaccounts"] = AccM.getListAccount();
        //            return View("ManageAccounts");
        //        }

        //    }
        //    return RedirectToAction("Index", "Home");
        //}
        //private LENGKENG_ICECREAM_DBEntities de = new LENGKENG_ICECREAM_DBEntities();

        //[HttpGet]
        //public ActionResult deleteAccount(string id)
        //{

        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1 && user.UserName != id)
        //        {
        //            AccM.deleteAccount(id);

        //        }

        //        return RedirectToAction("manageAccounts");
        //    }
        //    return RedirectToAction("Index", "Home");
            
        //}

        [HttpGet]
        public ActionResult sendSupport()
        {
            return View("SupportUser", new SupportModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult sendSupport(SupportModel model)
        {
            UserSession user = SessionHelper.getSesstion();
            if (user != null)
            {
                model.USERNAME = user.UserName;
                model.SDATECREATE = DateTime.Now;
                if (ModelState.IsValid)
                {
                    AccM.addSupport(model);
                    ModelState.AddModelError(string.Empty, "Cám ơn bạn đã gửi thư đóng góp");
                    return View("SupportSucccess");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

                    return View("SupportUser",model);
                }
            }
            else
            {
                return RedirectToAction("LoginAccount");
            }
            
        }

        public ActionResult addShopping(string id)
        {
            SCart.addListShoppingCart(id);
            //if(ShoppingHelper.getSesstion() == null)
            return Json(SCart.getAmount(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult getCartView()
        { 

LengKeng/Views/Accounts/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model LengKeng.Models.ChangePasswordModel

<div id="content_fullsize">
    <span id="Login_content_title">Thay đổi mật khẩu</span>

    @using (Html.BeginForm("ChangePassword", "Accounts", FormMethod.Post))
    {
       @Html.AntiForgeryToken();
    @Html.ValidationSummary("Mật khẩu không đúng")

    <div class="Register_row">
        <div class="Register_row_left">
            <label class="lblstyle">Mật khẩu cũ: </label>
        </div>
        <div class="Register_row_right">

            @Html.PasswordFor(model => model.OldPassword, new { @class = "txtstyle" })


            @Html.ValidationMessageFor(model => model.OldPassword)


        </div>
    </div>
    <div class="Register_row">
        <div class="Register_row_left">
            <label class="lblstyle">Mật khẩu mới: </label>
        </div>
        <div class="Register_row_right">
            <div>
                @Html.PasswordFor(model => model.NewPassword, new { @class = "txtstyle" })
            </div>

            <div align="center">
                @Html.ValidationMessageFor(model => model.NewPassword)
            </div>

        </div>
    </div>
    <div class="Register_row">
        <div class="Register_row_left">
            <label class="lblstyle">Nhập lại: </label>
        </div>
        <div class="Register_row_right">
            <div>
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "txtstyle" })
            </div>

            <div align="center">
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>

        </div>
    </div>


        <input class="btnstyle" id="btnSubmitRecoveryPass" type="submit" value="Thay đổi" name="btnLogin">
    }
        
     

</div>
 <style type="text/css">
    /* Styles for validation helpers*/
    .field-validation-error {
        color: red;
    }

    .field-validation-valid {
        display: none;
        text-align: center;
    }

    .input-validation-error {
        border: 1px solid #ff0000 !important;
        background-color: #ffeeee !important;
    }

    .validation-summary-errors {
        font-weight: bold !important;
        color: red !important;
        text-align: center;
        font-size: 16px;
    }

    .validation-summary-valid {
        display: none;
    }
</style>

LengKeng/Views/Accounts/ChangePasswordSuccess.cshtml
@{
    ViewBag.Title = "ChangePasswordSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content_fullsize">

    <span id="Login_content_title">Thay đổi mật khẩu thành công</span>
</div>

LengKeng/Views/Accounts/DetailAccount.cshtml
@{
    ViewBag.Title = "DetailAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model LengKeng.Models.ProfileUserModel
@using LengKeng.Models
@using LengKeng.Code
@{
    
    ProfileUserModel acc = (ProfileUserModel)ViewData["acc"];
    String admin;
}

<div id="content_fullsize">
    <span id="Login_content_title">Thông tin tài khoản</span>
    <div id="Register_content_border">
        @using (Html.BeginForm("updateAccount", "Accounts", FormMethod.Post))
        {

            <span class="Register_label_information">Thông tin đăng nhập</span>
            <div class="Register_row_bottom"></div>

            <div class="Register_row">
                <div class="Register_row_left">

                    <label class="lblstyle">Tên đăng nhập :</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.username</label>

                </div>
            </div>
           
                
            

            <span class="Register_label_information">Thông tin cá nhân</span>
            <div class="Register_row_bottom"></div>

            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Họ và Tên:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.fullname</label>

                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Giới tính:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.sex</label>


                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Email:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.email</label>
                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Số điện thoại:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.phonenumber</label>

                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Ngày sinh:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.bday</label>
                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Địa chỉ:</label>
                </div>
                <div class="Register_row_right">
                    <label class="lblaccount">@acc.address</label>
                </div>
            </div>

            <div>
                <input class="btnstyle" id="btnDoneUpdate" type="submit" value="Cập nhật" name="btnDoneUpdate">
            </div>
            
        }
    </div>

</div>

LengKeng/Views/Accounts/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model LengKeng.Models.LoginModel


<div id="content_fullsize">
    <span id="Login_content_title">Đăng nhập</span>
    <div id="Register_content_border">
        @using (Html.BeginForm())
        {

            @Html.AntiForgeryToken();
            @Html.ValidationSummary(true, "Username hoặc Password không đúng")

            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Tên đăng nhập: </label>
                </div>
                <div class="Register_row_right">
                    
                        @Html.TextBoxFor(model => model.UserName, new { @class = "txtstyle" })
                    
                    
                        @Html.ValidationMessageFor(model => model.UserName)
                    
                    
                </div>
            </div>
            <div class="Register_row">
                <div class="Register_row_left">
                    <label class="lblstyle">Mật khẩu: </label>
                </div>
                <div class="Register_row_right">
                   <div>
                       @Html.PasswordFor(model => model.Password, new { @class = "txtstyle"})
                   </div>
                        
                    <div align="center">
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>
                    
                </div>
            </div>




            @*<div class="checkboxRememberLogin">
                    <input type="checkbox" id="chbxsearchLogin" name="RememberLogin" value="true">
                    <label for="chbxsearchLogin"></label>
                </div>
                <label id="lblRememberLogin">Duy trì đăng nhập</label>*@

            <input class="btnstyle" id="btnLogin" type="submit" value="Đăng nhập" name="btnLogin">
            <br>
            <div id="recovery_password">
                <a href="@Url.Action("RecoverPassword", "Accounts")">Quên mật khẩu</a>
            </div>

        }

        <div class="fb-login-button" id="btnLogin"  scope="public_profile,email" onlogin="checkLoginState();" data-max-rows="1" data-size="large" data-show-faces="false" data-auto-logout-link="false"></div>
    </div>
       
    <div id="status">
    </div>
</div>


<style type="text/css">
    /* Styles for validation helpers*/
    .field-validation-error {
        color: red;
        
    }

    .field-validation-valid {
        display: none;
        text-align: center;
    }

    .input-validation-error {
        border: 1px solid #ff0000 !important;
        background-color: #ffeeee !important;
        
    }

    .validation-summary-errors {
        font-weight: bold !important;
        color: red !important;
        text-align: center;
        font-size: 16px;
    }

    .validation-summary-valid {
        display: none;
        
    }
</style>

<script>
    // This is called with the results from from FB.getLoginStatus().
    function statusChangeCallback(response) {
        
        // The response object is returned with a status field that lets the
        // app know the current login status of the person.
        // Full docs on the response object can be found in the documentation
        // for FB.getLoginStatus().
        if (response.status === 'connected') {
            
            FB.api('/me', { fields: 'email' }, function (response) {

               
                var email = response.email;
                 


                 $.ajax({
                     url: '@Url.Action("LoginBySocial", "Accounts")',
                     type: 'POST',

                     // we set cache: false because GET requests are often cached by browsers
                     // IE is particularly aggressive in that respect
                     cache: false,
                     data: {email: email},
                     success: function (data) {

                        
                         window.location = data;

                     },
                     error: function () {
                         alert('Đã xảy ra lỗi trong quá trình đăng nhập bằng Facebook. Thử lại sau');

                     }
                 });
            });
            // Logged into your app and Facebook.
            
        } else if (response.status === 'not_authorized') {
            // The person is logged into Facebook, but not your app.
            document.getElementById('status').innerHTML = 'Please log ' +
              'into this app.';
        } else {
            // The person is not logged into Facebook, so we're not sure if
            // they are logged into this app or not.
            document.getElementById('status').innerHTML = 'Please log ' +
              'into Facebook.';
        }
    }

    // This function is called when someone finishes with the Login
    // Button.  See the onlogin handler attached to it in the sample
    // code below.
    function checkLoginState() {
        FB.getLoginStatus(function (response) {
            statusChangeCallback(response);
        });


    }

    window.fbAsyncInit = function () {
        FB.init({
            appId: '1393036270995368',
            cookie: true,  // enable cookies to allow the server to access
            // the session
            xfbml: true,  // parse social plugins on this page
            version: 'v2.5' // use version 2.2
        });

    };

    // Load the SDK asynchronously
   (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5&appId=1393036270995368";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    // Here we run a very simple test of the Graph API after login is
    // successful.  See statusChangeCallback() for when this call is made.

</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

LengKeng/Views/Accounts/ManageAccounts.cshtml
@{
    ViewBag.Title = "ManageAccounts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using LengKeng.Models
@using LengKeng.Code
<div id="content_fullsize">
    <span id="cart_content_title">Quản lý tài khoản người dùng</span>

    <div id="table_customers" align="center">
        <table>
            <tr>
                <th>STT</th>
                <th>ID</th>
                <th>Quyền</th>
                <th>Họ tên</th>
                <th>Email</th>
                <th>Số điện thoại</th>
                <th colspan="2">Chức năng</th>

            </tr>
            @{
                int i = 0;
                UserSession user = SessionHelper.getSesstion();
            }

            @foreach (ACCOUNTS acc in (List<ACCOUNTS>)ViewData["ListAccounts"])
            {

                <tr>
                    <td>@i</td>
                    <td class="textBold_table"> @acc.USERNAME </td>
                    @if (acc.ADMIN == 1)
                    {
                        <td>
                            Admin
                        </td>
                    }
                    else
                    {
                        <td>
                            User
                        </td>
                    }
                    <td>@acc.FULLNAME </td>
                    <td>@acc.EMAIL </td>
                    <td>@acc.PHONENUMBER</td>
                    <td>@Html.ActionLink("Chi tiết", "detailAccount/" + acc.USERNAME, "Accounts")</td>
                    @if (user.UserName != acc.USERNAME)
                    {
                        <td>@Html.ActionLink("Xoá", "deleteAccount/" + acc.USERNAME, "Accounts", new { onclick = "return confirm('Bạn có chắc muốn xoà tài khoản này?')" })</td>
                    }
                        
                </tr>
                    i += 1;
            }

            <tr>
                <td>@Html.ActionLink("+", "registerAccount", "Accounts")</td>
            </tr>
        </table>
    </div>

</div>

LengKeng/Views/Accounts/ManageBill.cshtml
@{
    ViewBag.Title = "ManageBill";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using LengKeng.Models
<div id="content_fullsize">
    <span id="cart_content_title">Quản lý đơn đặt hàng</span>

    <div id="table_customers" align="center">
        <table>
            <tr>
                <th>STT</th>
                <th>ID</th>
                <th>Ngày tạo</th>
                <th>Tổng giá</th>
                <th>Tình trạng</th>
                <th >Chức năng</th>

            </tr>
            @{
                int i = 0;
              
            }

            @foreach (BILL bill in (List<BILL>)ViewData["listbill"])
            {

                <tr>
                    <td>@i</td>
                    <td class="textBold_table"> @bill.USERNAME </td>
                   
                    <td>@Html.ActionLink(@bill.BDATECREATE.ToString(), "detailHistoryBill/" + bill.BID, "Accounts")</td>
                    <td>@bill.BTOTAL </td>
                    <td>@bill.BSTATUS </td>
                    @if (@bill.BSTATUS == "Chưa thanh toán")
                    {
                        <td>@Html.ActionLink("Xác nhận", "confirmPay/" + bill.BID, "Accounts")</td>
                    }
                    else
                    {
                        <td></td>
                    }
                    
                    

                </tr>
                    i += 1;
            }

           
        </table>
    </div>

</div>

LengKeng/Views/Accounts/PaySuccess.cshtml
@{
    ViewBag.Title = "PaySuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content_fullsize">

    <span id="Login_content_title">Bạn đã đặt mua thành công</span>
</div>

LengKeng/Views/Accounts/RecoverPassword.cshtml
@{
    ViewBag.Title = "RecoverPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model LengKeng.Models.ResetPasswordModel

<div id="content_fullsize">
    <span id="Login_content_title">Thay đổi mật khẩu</span>

    @using (Html.BeginForm("RecoverPassword", "Accounts", FormMethod.Post))
    {
        @Html.AntiForgeryToken();
        @Html.ValidationSummary("Tên đăng nhập không tồn tại")

        <div class="Register_row">
            <div class="Register_row_left">
                <label class="lblstyle">Tên đăng nhập: </label>
            </div>
            <div class="Register_row_right">

                @Html.TextBoxFor(model => model.UserName, new { @class = "txtstyle" })


                @Html.ValidationMessageFor(model => model.UserName)


            </div>
        </div>
        


        <input class="btnstyle" id="btnSubmitRecoveryPass" type="submit" value="Thay đổi" name="btnLogin">
    }



</div>
<style type="text/css">
    /* Styles for validation helpers*/
    .field-validation-error {
        color: red;
    }

    .field-validation-valid {
        display: none;
        text-align: center;
    }

    .input-validation-error {
        border: 1px solid #ff0000 !important;
        background-color: #ffeeee !important;
    }

    .validation-summary-errors {
        font-weight: bold !important;
        color: red !important;
        text-align: center;
        font-size: 16px;
    }

    .validation-summary-valid {
        display: none;
    }
</style>

LengKeng/Views/Accounts/ShoppingCart.cshtml
@{
    ViewBag.Title = "ShoppingCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div id="content_fullsize">
    <div id="_cart">@{Html.RenderAction("Cart", "Accounts");}</div>
    

    <div id="cart_content_btnPay">

        <button class="btnstyle" id="btnPay" type="submit" onclick="window.location.href='@Url.Action("payCart", "Accounts")'">Đặt mua</button>
        <button class="btnstyle" id="btnContinue" type="button" onclick="window.location.href='@Url.Action("Index","Home")'">Mua tiếp</button>
        
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $(".shoppingCart").hide();
    });

    function updateCart(id) {
        var quantity = $("#item_" + id).val();
        $.ajax({
            url: '@Url.Action("updateCartItem", "Accounts")',
            type: 'GET',

            // we set cache: false because GET requests are often cached by browsers
            // IE is particularly aggressive in that respect
            cache: false,
            data: { id: id, quantity: quantity },
            success: function (data) {

                $("#_cart").html(data);

            },
            error: function () {
                alert('đã có lỗi xảy ra. Vui lòng thử lại sau.');

            }
        });
    }

    function deleteItemCart(id) {
        var resultConfirm = confirm("Bạn có chắc muốn xoá món này ra khỏi giỏ?");
        if (resultConfirm) {
            $.ajax({
                url: '@Url.Action("deleteProductFromCart", "Accounts")',
                type: 'GET',

                // we set cache: false because GET requests are often cached by browsers
                // IE is particularly aggressive in that respect
                cache: false,
                data: { id: id },
                success: function (data) {

                    $("#_cart").html(data);

                },
                error: function () {
                    alert('đã có lỗi xảy ra. Vui lòng thử lại sau.');

                }
            });
        }
    }
</script>

LengKeng/Views/Accounts/SupportSucccess.cshtml
@{
    ViewBag.Title = "SupportSucccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content_fullsize">

    <span id="Login_content_title">Gửi phản hồi thành công</span>
</div>