LengKeng/Models/COMMENTS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LengKeng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public int CMID { get; set; }
        public string CMCONTENT { get; set; }
        public int IDPRODUCT { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> CDATECREATE { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual ACCOUNTS ACCOUNTS { get; set; }
    }
}

LengKeng/Controllers/AdminController.cs
using LengKeng.Code;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LengKeng.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            var user = SessionHelper.getSesstion();
            if (user == null)
            {
                return RedirectToAction("LoginAccount", "Accounts");
            }
            if (user.Admin != 1)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        [HttpPost]
        public void Upload()
        {
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                var fileName = Path.GetFileName(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                file.SaveAs(path);
            }

        }
    }
}

LengKeng/Controllers/ProductController.cs
using LengKeng.code;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LengKeng.Models;
using LengKeng.Code;

namespace LengKeng.Controllers
{
    public class ProductController : Controller
    {
        private CetagoryModelProcess db = new CetagoryModelProcess();
        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult detailProduct(string id)
        {
            ViewData["listDepartment"] = db.getListDepartment();
            ViewData["product"] = db.getProduct(id);
            db.tangView(id);

            return View("DetailProduct", new CommentModel());
        }


        [HttpPost]
        public ActionResult addComent(string pid, string username, string commentContent)
        {

            CommentModel temp = new CommentModel();
            temp.CMCONTENT = commentContent;
            temp.IDPRODUCT = Int32.Parse(pid);
            temp.USERNAME = username;

            db.writeComment(temp);
                return Comment(pid);
            

        }


        //public ActionResult mangeDetailProduct()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {


        //            ViewData["listProduct"] = db.getListProduct();

        //            return View("ManageListProduct");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}

        //[HttpGet]
        //public ActionResult addProduct()
        //{
        //    return View("AddProduct", new ProductModel());
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult addProduct(ProductModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        int id = db.addProduct(model);

        //        return RedirectToAction("detailProduct/" + id);
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("AddProduct", model);
        //    }
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult manageUpdateProduct(ProductModel model)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        db.updateProduct(model);

        //        return RedirectToAction("detailProduct/" + model.PID);
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("ManageUpdateProduct", model);
        //    }


        //}

        //[HttpGet]
        //public ActionResult manageUpdateProduct(string id)
        //{
        //    ProductModel model = db.getProductModel(id);
        //    return View("ManageUpdateProduct", model);
        //}

        //public ActionResult mangeCategory()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {

        //            ViewData["listCategory"] = db.getListCategory();
        //            return View("ManageCatagory");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}

        //public ActionResult deleteCategory(string id)
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            db.deleteCategory(id);
        //            return RedirectToAction("mangeCategory");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}

        //[HttpGet]
        //public ActionResult updateCategory(string id)
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            CategoryModel model = db.getCategory(id);
        //            return View("UpdateCategory", model);
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult updateCategory(CategoryModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.updateCategory(model);
        //        return RedirectToAction("mangeCategory");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("UpdateCategory", model);
        //    }

        //}

        //[HttpGet]
        //public ActionResult addCategory()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            return View("AddCategory", new CategoryModel());
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult addCategory(CategoryModel model)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.addCategory(model);
        //        return RedirectToAction("mangeCategory");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("AddCategory", model);
        //    }

        //}

        //public ActionResult mangeDepartment()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {

        //            ViewData["listDepartment"] = db.getListDepartment();
        //            return View("ManageDepartment");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}

        //[HttpGet]
        //public ActionResult addDepartment()
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            return View("AddDepartment", new DepartmentCategory());
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult addDepartment(DepartmentCategory model)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.addDepartment(model);
        //        return RedirectToAction("mangeDepartment");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("AddDepartment", model);
        //    }
        //}

        //[HttpGet]
        //public ActionResult updateDepartment(string id)
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)
        //    {
        //        if (user.Admin == 1)
        //        {
        //            DepartmentCategory model = db.getDepartment(id);
        //            return View("UpdateDepartment", model);
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index", "Home");
        //        }
        //    }
        //    else
        //    {
        //        return RedirectToAction("LoginAccount"); ;
        //    }
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult updateDepartment(DepartmentCategory model)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.updateDepartment(model);
        //        return RedirectToAction("mangeDepartment");
        //    }
        //    else
        //    {
        //        ModelState.AddModelError(string.Empty, "Vui lòng nhập đầy đủ thông tin");

        //        return View("UpdateDepartment", model);
        //    }
        //}


        //public ActionResult deleteDepartment(string id)
        //{
        //    UserSession user = SessionHelper.getSesstion();
        //    if (user != null)

LengKeng/Views/Shared/Comment.cshtml
@model LengKeng.Models.CommentModel
@using LengKeng.Models
@using LengKeng.Code
<div id="comment_border">
    <div id="title_comment_border">Bình luận - Nhận xét</div>

    <div id="area_comment">
        @{
            
            List<COMMENTS> listCom = ViewData["listComment"] as List<COMMENTS>;
            foreach (COMMENTS com in listCom)
            {
                <div id="comment">
                    <span id="username_comment">@com.USERNAME - <i>(@com.CDATECREATE)</i> </span>
                    <br />
                     <span>@com.CMCONTENT</span>
                </div>
            }
        }
    </div>

    <div id="area_post_comment">
        @{
            UserSession user = SessionHelper.getSesstion();
            if (user != null)
            {
                using (Html.BeginForm("detailProduct", "Product", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
            @Html.Hidden("IDPRODUCT", ViewBag.PID as String)
            @Html.Hidden("USERNAME", user.UserName)

            <div>
                @Html.TextAreaFor(m => m.CMCONTENT, new { @class = "txtArea", style = "width:530px; height: 50px;", @Placeholder = "Thêm bình luận....." })
            </div>
            <div align="center" class="field-validation-error">
                
            </div>
            <input class="btnstyle" id="btnPostComment" type="button" value="Đăng" onclick="sendComment('@ViewBag.PID', '@user.UserName');"/>
                }

            }
            else
            {

                <span id="comment_detail">
                    Vui lòng
                    <a href="@Url.Action("LoginAccount", "Accounts")">Đăng nhập</a>
                    hoặc <a href="@Url.Action("registerAccount", "Accounts")">Đăng kí</a>
                    tài khoản để có thể bình luận
                </span>

            }
        }

    </div>

</div>

LengKeng/Views/Shared/PartialSidebar.cshtml
@using LengKeng.Models
@{
    List<DEPARTMENTS> listDe = (List<DEPARTMENTS>)ViewData["listDepartment"];

}

<div id="sidebar">
    <dl>
        <dt id="menu_sidebar">MENU</dt>
        @foreach (DEPARTMENTS tempDe in listDe)
        {
            <dt class="list_menu"><a href="@Url.Action("Index", "Home", new { id1 = @tempDe.DID, id2 = "De" })">@tempDe.DNAME</a></dt>

            List<CATELOGIES> listCa = tempDe.CATELOGIES.Cast<CATELOGIES>().ToList();
            foreach (CATELOGIES tempCa in listCa)
            {
                <dd>
                    <a href="@Url.Action("Index", "Home", new { id1 = @tempCa.CID, id2 = "Ca" })">@tempCa.CNAME</a>
                </dd>
            }
        }
    </dl>
    
</div>

LengKeng/Views/Shared/_Layout.cshtml
@using LengKeng.Code
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Leng Keng</title>
    <link rel="stylesheet" href="~/Content/LengKeng_themes/css/style_1.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/LengKeng_themes/css/SliderBanner/style.css" />
    <script type="text/javascript" src="~/Content/LengKeng_themes/css/SliderBanner/jquery.js"></script>
    <link href="~/Content/LengKeng_themes/css/PagedList.css" rel="stylesheet" />
</head>
<body>
    <div id="out_source">
        <div id="header_top">
            <div id="in_left">
                <div id="search">
                    @using (Html.BeginForm("Search","Home"))
                    {
                        <input type="text" id="txtsearch" name="txtsearch" size="21" maxlength="120" placeholder="món nào...?">
                        <input type="submit" value=" " id="btnsearch">
                        
                    }
                </div>
            </div>
            @{
                UserSession user = SessionHelper.getSesstion();
                LengKeng.code.ShoppingCart cart = new LengKeng.code.ShoppingCart();
                if (user != null)
                {
                    //string count = user.CountShopping.ToString();
                    
                    


                        <div id="in_right_">
                            <ul id="nav">
                                <li>
                                    <a class="shoppingCart" href="@Url.Action("getCartView", "Accounts")">
                                        <span>Giỏ hàng: </span>
                                        <span id="spnCart" class="carteffect">@cart.getAmount() </span>
                                        <span class="carteffect"> Item(s)</span>
                                    </a>
                                </li>
                                <li class="shoppingCart">
                                    ●
                                </li>
                                <li>
                                    @Html.ActionLink("Welcome " + @user.UserName, "detailAccount", "Accounts")
                                    <ul class="dropdown">

                                        <li>@Html.ActionLink("Lịch sử mua hàng", "historyCart", "Accounts")</li>
                                        @{
                    if (user.isSocial == 0)
                    {
                                    <li>@Html.ActionLink("Đổi mật khẩu", "ChangePassword", "Accounts")</li>
                    }
                    if (user.Admin == 1)
                    {
                        <li>@Html.ActionLink("Trang quản lý", "Index", "Admin")</li>
                    }
}
                                        <li>@Html.ActionLink("Đăng xuất", "Logout", "Accounts")</li>
                                        

                                    </ul>
                                </li>


                            </ul>

                        </div>


                    



                }
                else
                {
                    <div id="in_right">
                        @Html.ActionLink("Đăng kí", "registerAccount", "Accounts")
                        <span id="slash">|</span>
                        @Html.ActionLink("Đăng nhập", "LoginAccount", "Accounts")
                        <span id="slash" class="shoppingCart">●</span>
                        <a class="shoppingCart" href="@Url.Action("getCartView", "Accounts")">
                            <span>Giỏ hàng: </span>
                            <span id="spnCart" class="carteffect">@cart.getAmount() </span>
                            <span class="carteffect"> Item(s)</span>
                        </a>
                    </div>
                }
            }

        </div>
        <div id="header_logo">
            <a href="@Url.Action("Index","Home")">
                <img src="~/Content/LengKeng_themes/imgs/logo_moi1.gif" alt="header_left">
            </a>
        </div>
    </div>
    <div id="source">
        <div id="header">
            <div id="header_center">
                <div id="on_center">
                    <div id="wowslider-container1">
                        <div class="ws_images">
                            <ul>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner0.png" alt="banner0" title="banner0" id="wows1_0" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner1.jpg" alt="banner1" title="banner1" id="wows1_1" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner3.jpg" alt="banner3" title="banner3" id="wows1_2" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner4.jpg" alt="banner4" title="banner4" id="wows1_3" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner5.jpg" alt="banner5" title="banner5" id="wows1_4" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner6.jpg" alt="banner6" title="banner6" id="wows1_5" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner7.jpg" alt="banner7" title="banner7" id="wows1_6" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner8.jpg" alt="banner8" title="banner8" id="wows1_7" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/banner9.jpg" alt="banner9" title="banner9" id="wows1_8" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/chocolate+week+ice+cream+sandwich.jpg" alt="chocolate+week+ice+cream+sandwich" title="chocolate+week+ice+cream+sandwich" id="wows1_9" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/coppettelecestinecolorate.jpg" alt="coppettelecestinecolorate" title="coppettelecestinecolorate" id="wows1_10" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/cover.jpg" alt="cover" title="cover" id="wows1_11" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/desert6a_1.jpg" alt="desert6a_1" title="desert6a_1" id="wows1_12" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/dessertb6_1.jpg" alt="dessertb6_1" title="dessertb6_1" id="wows1_13" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/icecreammodbanner.png" alt="icecreammodbanner" title="icecreammodbanner" id="wows1_14" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/ics.jpg" alt="wordpress slider" title="ics" id="wows1_15" /></li>
                                <li><img src="~/Content/LengKeng_themes/imgs/banner/images/imglowfaticecream.png" alt="imglowfaticecream" title="imglowfaticecream" id="wows1_16" /></li>
                            </ul>
                        </div>
                        <div class="ws_bullets">
                            <div>
                                <a href="#" title="banner0"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner0.png" alt="banner0" />1</span></a>
                                <a href="#" title="banner1"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner1.jpg" alt="banner1" />2</span></a>
                                <a href="#" title="banner3"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner3.jpg" alt="banner3" />3</span></a>
                                <a href="#" title="banner4"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner4.jpg" alt="banner4" />4</span></a>
                                <a href="#" title="banner5"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner5.jpg" alt="banner5" />5</span></a>
                                <a href="#" title="banner6"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner6.jpg" alt="banner6" />6</span></a>
                                <a href="#" title="banner7"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner7.jpg" alt="banner7" />7</span></a>
                                <a href="#" title="banner8"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner8.jpg" alt="banner8" />8</span></a>
                                <a href="#" title="banner9"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/banner9.jpg" alt="banner9" />9</span></a>
                                <a href="#" title="chocolate+week+ice+cream+sandwich"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/chocolate+week+ice+cream+sandwich.jpg" alt="chocolate+week+ice+cream+sandwich" />10</span></a>
                                <a href="#" title="coppettelecestinecolorate"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/coppettelecestinecolorate.jpg" alt="coppettelecestinecolorate" />11</span></a>
                                <a href="#" title="cover"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/cover.jpg" alt="cover" />12</span></a>
                                <a href="#" title="desert6a_1"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/desert6a_1.jpg" alt="desert6a_1" />13</span></a>
                                <a href="#" title="dessertb6_1"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/dessertb6_1.jpg" alt="dessertb6_1" />14</span></a>
                                <a href="#" title="icecreammodbanner"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/icecreammodbanner.png" alt="icecreammodbanner" />15</span></a>
                                <a href="#" title="ics"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/ics.jpg" alt="ics" />16</span></a>
                                <a href="#" title="imglowfaticecream"><span><img src="~/Content/LengKeng_themes/imgs/banner/tooltips/imglowfaticecream.png" alt="imglowfaticecream" />17</span></a>
                            </div>
                        </div>
                        <div class="ws_shadow"></div>
                    </div>
                    <script type="text/javascript" src="~/Content/LengKeng_themes/css/SliderBanner/wowslider.js"></script>
                    <script type="text/javascript" src="~/Content/LengKeng_themes/css/SliderBanner/script.js"></script>
                </div>
                <div id="on_bottom">
                    <div class="header_menu">
                        @Html.ActionLink("Trang chủ", "Index/" + "Kem viên", "Home")
                    </div>
                    <div class="header_menu">
                        @Html.ActionLink("Giới thiệu", "getInformation", "Home")
                    </div>

                    <div class="header_menu">
                        @Html.ActionLink("Hỗ trợ", "sendSupport", "Accounts")

                    </div>
                    <div class="header_menu">

                        <a href="https://www.facebook.com/groups/371181323080251/">
                            Liên hệ
                        </a>
                    </div>
                </div>
            </div>
            <div id="header_bottom">
            </div>
        </div>

        @RenderBody()

        <div id="footer">
            <a href="https://www.facebook.com/groups/371181323080251/">
                &copy; Designed by LengKeng Team
            </a>
        </div>
    </div>
</body>
</html>

LengKeng/Views/Shared/cart.cshtml
@{
    ViewBag.Title = "cart";
}


@using LengKeng.Models

@{
    List<PRODUCTS> listBill = (List<PRODUCTS>)ViewData["listCart"];
    List<int> listAmount = (List<int>)ViewData["listAmonut"];
}
<span id="cart_content_title">Quản lý giỏ hàng</span>

<div id="cart_content_cart_table">
    <div id="cart_content_titlebar">
        <span id="cart_content_titlebar_pname">Sản phẩm</span>
        <span id="cart_content_titlebar_psavor">Mùi vị</span>
        <span id="cart_content_titlebar_pprice">Đơn giá</span>
        <span id="cart_content_titlebar_pamount">Số lượng</span>
        <span id="cart_content_titlebar_ptotalprice">Thành tiền</span>
        <span id="cart_content_titlebar_action"></span>
    </div>
    @for (int i = 0; i < listBill.Count; i++)
    {

        <div class="cart_content_row">
            <div class="cart_content_row_pname">
                <img src="@Url.Content(@listBill[i].PIMG)" alt="@listBill[i].PNAME">
                <div class="cart_content_row_pname_name">@listBill[i].PNAME</div>
            </div>
            <div class="cart_content_row_psavor">
                <p>@listBill[i].PSAVOUR</p>
            </div>

            <div class="cart_content_row_pprice">
                <p>@listBill[i].PCOST Vnđ</p>

            </div>

            <div class="cart_content_row_pamount">
                <form>
                    <input id="item_@i" class="input_text" step="1" type="number" onchange ="updateCart('@i')" value="@listAmount[i].ToString()" />
                </form>
            </div>

            <div class="cart_content_row_ptotalprice">
                @{var price = listBill[i].PCOST * listAmount[i];
                          <p>@price</p>}
            </div>
            <div class="cart_content_row_ptotalprice">
                
                <a onclick="deleteItemCart('@i')">Xoá</a>
            </div>
        </div>
    }



</div>

<div id="cart_content_total">
    <span id="cart_content_total_title">Tổng giá:</span>
    <span id="cart_content_total_price">@ViewData["Total"] Vnđ</span>
</div>